language: node_js
node_js:
  - "7.6.0"
install:
  - npm install
deploy:
  provider: releases
  user: $GIT_USERNAME
  password: $GIT_PASSWORD
  file: "/dist/installers/money-manager-desktop_0.0.0_amd64.deb"
  skip_cleanup: true
  branches:
      only:
      - /^v\d+(\.\d+)+$/
  on:
    tags: true
after_success:
  - npm run build-electron
  - npm run package-linux
  - npm run installer-deb64
